version: '2'
services:
    foodnet-app:
        image: foodnet
        external_links:
            - foodnet-cassandra:cassandra
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra
            - JHIPSTER_SLEEP=30 # gives time for the Cassandra cluster to start and execute the migration scripts
        ports:
            - 8080:8080
    foodnet-cassandra:
        extends:
            file: cassandra-cluster.yml
            service: foodnet-cassandra
    foodnet-cassandra-node:
        image: cassandra:3.9
        links:
            - foodnet-cassandra:seed
        environment:
            - CASSANDRA_SEEDS=seed
    foodnet-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: foodnet-cassandra-migration
        links:
            - foodnet-cassandra
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
